# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  androidVersion:

steps:

- powershell: |
   $buildSourceBranch = "$(Build.SourceBranch)"
   $tagVersion = $buildSourceBranch.Substring($buildSourceBranch.LastIndexOf("/") + 2)
   
   $regex = "([0-9]+).([0-9]+).([0-9]+)(-pre([0-9]+))?$"
   if(($tagVersion -match $regex) -eq $false) {
       Write-Error "Tag version not in correct format; Expected x.y.z(-label) , actual $tagVersion"
   }
   
   Write-Host("Branch = $buildSourceBranch, Version = $tagVersion");
   Write-Output ("##vso[task.setvariable variable=androidVersion;]$tagVersion")
  displayName: 'Get Version from tag'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: android-manifest-version@1
  inputs:
    sourcePath: 'src/Plantish.Android/Properties/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionName: '$(androidVersion)'
    printFile: true

- task: XamarinAndroid@1
  displayName: 'Build Android'
  inputs:
    projectFile: src/Plantish.Android/Plantish.Android.csproj
    configuration: '$(BuildConfiguration)'
    createAppPackage: true
    msbuildVersionOption: latest
    msbuildArguments: ' /p:JavaSdkDirectory="$(JAVA_HOME)" '

- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) src/Plantish.Android/bin/release/*.apk'
  inputs:
    apkFiles: 'src/Plantish.Android/bin/release/*.apk'
    apksignerKeystoreFile: 'hmo keystore.keystore'
    apksignerKeystorePassword: '$(keystore_pw)'
    apksignerKeystoreAlias: '$(keystore_alias)'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'Håvard Moås AppCenter Privat Github login'
    appSlug: '$(AppSlug)'
    appFile: 'src/Plantish.Android/bin/release/com.haavamoa.plantish.apk'
    releaseNotesOption: 'input'
    destinationType: 'store'
    destinationStoreId: '$(GoogleStoreBetaId)'



